github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
plugins:
  - jekyll-remote-theme
remote_theme: chriswitkowski/forty-jekyll-theme
gfm_quirks: paragraph_end
title: Welcome to Lego Josh!
description: A site to share my adventures